apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: vjsonserver-v1.kb.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-example-com-v1-jsonserver
  failurePolicy: Fail
  rules:
  - apiGroups:
    - example.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jsonservers
  sideEffects: None